# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('polenta_rcpp_hello', PACKAGE = 'polenta')
}

Cmatrix <- function(msa) {
    .Call('polenta_Cmatrix', PACKAGE = 'polenta', msa)
}

nChoosek <- function(n, k) {
    .Call('polenta_nChoosek', PACKAGE = 'polenta', n, k)
}

which_true <- function(x) {
    .Call('polenta_which_true', PACKAGE = 'polenta', x)
}

add_msa <- function(ref, com) {
    .Call('polenta_add_msa', PACKAGE = 'polenta', ref, com)
}

