# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cmatrix_p <- function(mat) {
    .Call('polenta_Cmatrix_p', PACKAGE = 'polenta', mat)
}

Cmatrix <- function(msa) {
    .Call('polenta_Cmatrix', PACKAGE = 'polenta', msa)
}

nChoosek <- function(n, k) {
    .Call('polenta_nChoosek', PACKAGE = 'polenta', n, k)
}

which_true <- function(x) {
    .Call('polenta_which_true', PACKAGE = 'polenta', x)
}

which_true2 <- function(x) {
    .Call('polenta_which_true2', PACKAGE = 'polenta', x)
}

add_msa_score <- function(ref, com) {
    .Call('polenta_add_msa_score', PACKAGE = 'polenta', ref, com)
}

rps_mat_maker <- function(nr, nc) {
    .Call('polenta_rps_mat_maker', PACKAGE = 'polenta', nr, nc)
}

add_msa_sc <- function(msa, ref) {
    .Call('polenta_add_msa_sc', PACKAGE = 'polenta', msa, ref)
}

