# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nChoosek <- function(n, k) {
    .Call('_polenta_nChoosek', PACKAGE = 'polenta', n, k)
}

msa_recode <- function(msa) {
    .Call('_polenta_msa_recode', PACKAGE = 'polenta', msa)
}

res_pair_hit <- function(col2res) {
    .Call('_polenta_res_pair_hit', PACKAGE = 'polenta', col2res)
}

add_msa <- function(ref_col2res, alt_col2res, alt_res2col, hit_mat) {
    .Call('_polenta_add_msa', PACKAGE = 'polenta', ref_col2res, alt_col2res, alt_res2col, hit_mat)
}

